version: '3.8'

services:
  api:
    container_name: recruitment-backend-api
    platform: linux/x86_64
    # platform: linux/arm64/v8
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.dev
    ports:
      - 8080:80
    environment:
      XDEBUG_ENABLED: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_MAXNESTING_LEVEL: 1000
      XDEBUG_REMOTE_CONNECT_BACK: 1
    volumes:
      - ./:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/apache/apache2-ci.conf:/etc/apache2/apache2.conf
      - .docker/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: recruitment-backend-db
    platform: linux/x86_64
    # platform: linux/arm64/v8
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - recruitment-backend-db-data:/var/lib/mysql
      - ./.docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    container_name: recruitment-backend-phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 8033:80
    volumes:
      - ./.docker/phpmyadmin/sessions:/sessions
    depends_on:
      - db
    networks:
      - backend

  mailhog:
    container_name: recruitment-backend-mail
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend

volumes:
  recruitment-backend-db-data:
    driver: local
networks:
  backend:
    driver: bridge